image: python:3.8

pipelines:
  tags:
    release/*:
      - step:
          name: Build and upload package
          script:
            - pip install twine
            - python setup.py bdist_wheel
            - twine upload dist/*
