---
name: CI

on:
  push:
    tags: ["release/v*"]
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  package:
    name: "Build Package Distributions"
    strategy:
      matrix:
        os: [ macos-10.15, macos-11 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: "actions/checkout@v2"
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.9"
      - name: "Build distribution"
        run: |
          python -m pip install --upgrade pip
          python -m pip install build
          python -m build
      - name: Publish package
        if: startsWith(github.ref, 'refs/tags/release/v')
        run: |
          python -m pip install twine
          twine upload -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/*
